#!/bin/bash

# author: Ikuo Degawa
# last updated: 2014/04/02

# MySQLのスキーマとdiffを最新のものにするスクリプトです。

# パスワードをコンソールに打っているので
# Warningが出ますが無視して大丈夫です。
# Warning: Using a password on the command line interface can be insecure.

# 設定（各自書き換える）
db_root="root"
db_root_pass="root"

# 共通設定
# db_name="twoweeter"
db_host="localhost"

if [ $# -gt 1 ]; then
    echo "Too many arguments."
    exit 1
fi

case $1 in 
    "default" ) 
        db_name="twoweeter"
        db_user="developer"
        db_pass="dennoGUMI"
        ;;
    "test" ) 
        db_name="test_twoweeter"
        db_user="tester"
        db_pass="noGERRY"
        ;;
    * ) 
        db_name="twoweeter"
        db_user="developer"
        db_pass="dennoGUMI"
        ;;
esac

# schema
newest_schema="schema.sql"
mysql -u ${db_root} -p${db_root_pass} -e"
DROP DATABASE IF EXISTS ${db_name};
CREATE DATABASE IF NOT EXISTS ${db_name};
GRANT ALL ON ${db_name}.* TO ${db_user}@${db_host} IDENTIFIED BY '${db_pass}';
USE ${db_name};
SOURCE ${newest_schema};
"
echo 'Schema resetted.'
echo "Done!"

